### PR TITLE
master into develop

### PR DESCRIPTION
**Pull request by lsh-0**
this will synchronise the changes that have been made to `master` and bypassed `develop`.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
For the record, we only use `master` with this project since there are no builds or deployments independent from `elife-dashboard`.

**Comment by giorgiosironi** [comment]
Maybe we should drop the `develop` branch if nothing is using it? Not up for adding pipelines for this project, which is deprecated.

**Comment by lsh-0** [comment]
the whole project is deprecated??

feel free to drop `develop` branch, it's just confusing things

**Comment by giorgiosironi** [comment]
Terminology used in https://docs.google.com/spreadsheets/d/1VsCbpC6RC3gSE4q7pvzRlOXf2dBrH7_-ZUWyVJlml3o/edit#gid=0 is `legacy`, no new developments, only security updates.

**Pull request closed without merging**
